[project]
name = "prizma-to-brapa"
version = "0.1.0"
description = "Conversor de Alias da conotação PRIZMA para BRAPA."
authors = [
    {name = "Antônio César",email = "antonioazevedo.dev@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "tk (>=0.1.0,<0.2.0)",
    "pyinstaller (>=6.0.0,<7.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
